In [ ]:
# Exercise 1.A NumPy: Manipulating Arrays

In [3]:
import numpy as np

In [4]:
 ## Looping Through Arrays

In [5]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [6]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [7]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


In [9]:
# The first loop goes over the rows of arrA, so each "x" is a whole row. And multiplying it by 2 gives back an entire array with each value doubled. The seccond loop goes one level lower. For "y in x" ut pulls out each individual number from the row, so it prints each element doubled one at a time instead of a row.

In [11]:
for x in arrA:
    for y in x:
        loop_result = x * 2
print(loop_result)
# This prints the whole row doubled, not just one number. That's because we set loop_result to x*2 (the row) instead of y*2 (one element). Also, print is outside the loop, so it only shows the last value loop_result was set to.

[28 30 32]


In [12]:
## Joining and Stacking Arrays

In [13]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [14]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [15]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [16]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)
# Error: "all input arrays must have the same shape"
# joined_array_1 is shape (4, 3) and joined_array_2 is shape (2, 6).
# np.stack() requires arrays to be the exact same shape because it adds a new axis,
# so it can't combine arrays with different dimensions.

ValueError: all input arrays must have the same shape

In [17]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [18]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)
# This throws a shape mismatch error. When concatenating on axis=1, the arrays need to have
# the same number of rows. joined_array_1 has 4 rows but arrA only has 2 rows, so NumPy
# can't line them up side by side.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [19]:
h_stacked = np.hstack((arrA, arrA))
# hstack stacks arrays horizontally (side by side), joining them along columns.
print(h_stacked)

v_stacked = np.vstack((arrA, arrA))
# vstack stacks arrays vertically (on top of each other), joining them along rows.
print(v_stacked)

d_stacked = np.dstack((arrA, arrA))
# dstack stacks arrays depth-wise, adding a new third dimension to combine them.
print(d_stacked)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


In [20]:
## Splitting Arrays

In [21]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)
# Result: 2 arrays, each is 2-dimensional with shape (2, 3).
# joined_array_1 had 4 rows, so splitting into 2 gives two even chunks of 2 rows each.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [22]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# Result: 3 arrays, each is 2-dimensional.
# Since 4 rows can't divide evenly into 3, NumPy makes the first array have 2 rows
# and the other two arrays have 1 row each. Shapes: (2, 3), (1, 3), (1, 3).

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


In [23]:
## Searching and Replacing Array Values

In [24]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


In [25]:
## Sorting and Filtering Arrays

In [26]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [27]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [28]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
