In [1]:
# Exercise 1.B NumPy Random

In [2]:
import numpy as np

In [3]:
## Generating Random Numbers

In [4]:
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[10  6]


In [5]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[11  8]]


In [6]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.7928913 ]
 [0.95971767]]


In [7]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[69 50 34 48 61]
 [25 83 59 47 36]
 [66 91 25 73 72]
 [32 76 36 70 46]]


In [8]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.8559436  0.33851295 0.57631439 0.71683364 0.34121128]
 [0.13637336 0.49088568 0.23597073 0.1863997  0.22196821]
 [0.05162629 0.24932065 0.30832245 0.60592171 0.48551939]
 [0.51409115 0.69737511 0.76725642 0.57145472 0.9988159 ]]


In [9]:
## Generating Random Choices from an Array

In [10]:
students = np.array(['Hamzah', 'Jake', 'Carlos', 'Diana', 'Ethan', 'Fatima',
                     'Gabriel', 'Hana', 'Isaiah', 'Jasmine', 'Kevin', 'Layla'])

In [11]:
call_on = np.random.choice(students)
print(call_on)

Hamzah


In [12]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)
# This wouldn't be an effective way to assign breakout groups because np.random.choice
# samples with replacement by default, meaning the same student can appear multiple times
# while others might not appear at all. For real breakout groups, you'd want each student
# assigned to exactly one group, which would require sampling without replacement.

[['Jake' 'Ethan' 'Jake' 'Jasmine']
 ['Hana' 'Hana' 'Isaiah' 'Isaiah']
 ['Diana' 'Jake' 'Hana' 'Carlos']]


In [14]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.15, 0.10, 0.10, 0.10, 0.05, 0.05, 0.05, 0.05, 0.05, 0.00, 0.00]
)
print(call_on_weighted)
# p values explained: Alex has a 30% chance (highest maybe they've been quiet lately
# and need to participate more). Brianna has 15%, Carlos through Ethan each have 10%,
# Fatima through Jasmine each have 5%, and Kevin and Layla have 0% (maybe they
# already presented today and don't need to be called on again).
# All p values must add up to 1.0.

['Ethan' 'Hamzah' 'Ethan' 'Jasmine' 'Hamzah']


In [15]:
## Generating a Normal Distribution

In [16]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[ 9.05739566  9.51657102 15.58065245 15.66970574 10.09449223]
 [ 2.95280315  4.77305423 10.99919764  9.52022695  5.73123341]
 [13.3480012  10.3559406  20.19920321 12.06574322 12.99910192]
 [15.79808718 15.35316753  7.55491903  4.52226561 17.08709082]]
